project_name: anima


builds:
  -
    binary: anima
    main: ./cmd/anima/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - 
    format_overrides:
      - goos: windows
        format: zip

    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'
