builds:
  - id: anima
    main: ./cmd/anima/main.go
    binary: anima
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
      - goos: windows
